development:
  adapter: postgresql
  encoding: utf8
  database: uatme_development
  pool: 5
  username: uatme
  password: uatmepass

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: uatme_test
  pool: 5
  username: uatme
  password: uatmepass